python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
python3 run.py --sim finalproject.py
